version: "3.8"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  fastapi:
    build: ./backend
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - elastic

  simulator:
    build: ./simulator
    command: ["python","generate_logs.py","--continuous"]
    volumes:
      - ./simulator:/sim
    depends_on:
      - elastic

# optional Redis for queue
  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  esdata:
